name: 2. CI/CD Pipeline for React App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

# NEW: Add top-level permissions for the whole workflow
permissions:
  contents: read
  pages: write      # Allows the workflow to write to GitHub Pages
  id-token: write   # Allows the workflow to authenticate for deployment

jobs:
  # Job 1: Build the site (this is mostly the same as before)
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Checkout Code
        uses: actions/checkout@v4

      - name: 2. Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: 3. Install Dependencies
        run: npm install

      - name: 4. Run Lint
        run: npm run lint

      - name: 5. Run Build
        run: npm run build

      # NEW: This step is no longer optional. We must configure pages.
      - name: 6. Setup Pages
        uses: actions/configure-pages@v4

      # NEW: We are uploading ONLY the 'dist' folder
      - name: 7. Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # This is the CRITICAL change:
          path: './dist' 

  # Job 2: Deploy the site (This is all new)
  deploy:
    # This job 'needs' (waits for) the 'build' job to finish
    needs: build

    # Grant permissions specifically for this deployment job
    permissions:
      pages: write
      id-token: write

    # Define the environment this deploys to
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }} # This will output the final URL

    runs-on: ubuntu-latest
    steps:
      - name: 1. Deploy to GitHub Pages
        # This is the official action to deploy the artifact to Pages
        uses: actions/deploy-pages@v4
        id: deployment
