name: 1. CI Pipeline (Build and Lint)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Checkout Code
        uses: actions/checkout@v4

      # --- THE FIX IS HERE ---
      - name: 2. Setup Node.js
        uses: actions/setup-node@v4
        with:
          # We'll use Node 20, the current LTS, to solve the 'File is not defined' error
          node-version: 20
      # --- END OF FIX ---

      - name: 3. Install Dependencies
        run: npm install

      - name: 4. Run Lint
        run: npm run lint

      - name: 5. Run Build
        run: npm run build

      - name: 6. List build output
        run: ls -la dist
