name: 1. CI Pipeline (Build and Lint)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Checkout Code
        uses: actions/checkout@v4

      - name: 2. Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # --- THE FIX IS HERE ---
      - name: 3. Install Dependencies
        # We are using 'npm install' instead of 'npm ci'
        # because this project does not have a package-lock.json
        run: npm install
      # --- END OF FIX ---

      - name: 4. Run Lint
        run: npm run lint

      - name: 5. Run Build
        run: npm run build

      - name: 6. List build output
        run: ls -la dist
